spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 175510239488-9enu3fk4j2ojkqo37m2jtguvbq31etfb.apps.googleusercontent.com
            client-secret: ozK9OHy1G9bLNmQ90DUl7dNs
          github:
            client-id: f22f07f916718970357b
            client-secret: 71a28c9158d5aeec8834415ad0368a0f752ccdf1
          facebook:
            client-id: 745822442185310
            client-secret: 1420ee09ae2935be1bfdfee43f4f0890
          okta:
            client-id: 0oadot51ctSY6p0GX0h7
            client-secret: ai4SRqsIpQq8X1SVl9BGKV1KDVhSsloO9ePrfQkm
        provider:
          okta:
            authorization-uri: https://dev-567179.oktapreview.com/oauth2/default/v1/authorize
            token-uri: https://dev-567179.oktapreview.com/oauth2/default/v1/token
            user-info-uri: https://dev-567179.oktapreview.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://dev-567179.oktapreview.com/oauth2/default/v1/keys

